#!/usr/bin/env php
<?php

$autoloadPath1 = __DIR__ . '/../../../autoload.php';
$autoloadPath2 = __DIR__ . '/../vendor/autoload.php';
if (file_exists($autoloadPath1)) {
    require_once $autoloadPath1;
} else {
    require_once $autoloadPath2;
}

use function BrainGames\gameEngine\{greetPlayer, isEven, launchGame};
use function BrainGames\gameEngine\{askGameQuestions, effectCalculations};
use function BrainGames\gameEngine\{checkAnswer, showMessage, findGCD};
use function BrainGames\gameEngine\{setArithmeticProgression, isPrimeNumber};
use function BrainGames\gameEngine\showProgressionWithHiddenElement;
use function BrainGames\gameEngine\setNumberForBrainEvenGame;
use function BrainGames\gameEngine\setDataForBrainCalcGame;
use function BrainGames\gameEngine\setNumbersForBrainGcdGame;
use function BrainGames\gameEngine\setNumberForBrainPrimeGame;

use function cli\line;
use function cli\prompt;

$gameType = 'brain-gcd';

launchGame($gameType);
