#!/usr/bin/env php
<?php

$autoloadPath1 = __DIR__ . '/../../../autoload.php';
$autoloadPath2 = __DIR__ . '/../vendor/autoload.php';
if (file_exists($autoloadPath1)) {
    require_once $autoloadPath1;
} else {
    require_once $autoloadPath2;
}

use function BrainEven\gameEngine\{greetPlayer, isEven, launchGame};
use function BrainEven\gameEngine\{askGameQuestions, effectCalculations};
use function BrainEven\gameEngine\{checkAnswer, showMessage};

use function cli\line;
use function cli\prompt;

$gameType = 'brain-even';

launchGame($gameType);
